#!/bin/bash
# Create a slideshow video from images + audio.
# Usage: ./make_video.sh <topic_dir> <audio_file> <output_file> [durations_file]
#
# durations_file: optional text file with one float (seconds) per line, one per image.
#   When provided, each image holds for its specified duration instead of uniform timing.
#   Generated by kokoro_tts.py --durations-out when using section-based TTS.

TOPIC_DIR="$1"
AUDIO="$2"
OUTPUT="$3"
DURATIONS_FILE="${4:-}"

if [ -z "$TOPIC_DIR" ] || [ -z "$AUDIO" ] || [ -z "$OUTPUT" ]; then
    echo "Usage: $0 <topic_dir> <audio_file> <output_file> [durations_file]"
    exit 1
fi

# Get audio duration
DURATION=$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "$AUDIO" | cut -d. -f1)
NUM_IMAGES=$(ls "$TOPIC_DIR"/img*.jpg 2>/dev/null | wc -l | tr -d ' ')

if [ "$NUM_IMAGES" -eq 0 ]; then
    echo "No images found in $TOPIC_DIR (expected img*.jpg)"
    exit 1
fi

if [ -z "$DURATION" ] || [ "$DURATION" -eq 0 ] 2>/dev/null; then
    echo "Error: could not read audio duration from $AUDIO"
    exit 1
fi

FADE=1

# Load per-image durations if provided
declare -a DURS
if [ -n "$DURATIONS_FILE" ] && [ -f "$DURATIONS_FILE" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
        DURS+=("$line")
    done < "$DURATIONS_FILE"
    echo "Using per-section durations from $DURATIONS_FILE"
fi

# Uniform fallback duration
UNIFORM_DUR=$(( (DURATION + NUM_IMAGES - 1) / NUM_IMAGES ))
if [ "$UNIFORM_DUR" -lt 2 ]; then UNIFORM_DUR=2; fi

echo "Audio: ${DURATION}s, Images: ${NUM_IMAGES}"

# Build ffmpeg inputs and filter graph
INPUTS=""
FILTER=""
i=0
for img in $(ls "$TOPIC_DIR"/img*.jpg | sort); do
    # Pick per-image duration: from durations file or uniform fallback
    if [ ${#DURS[@]} -gt "$i" ] && [ -n "${DURS[$i]}" ]; then
        # Round float up to nearest integer, minimum 2s
        D=$(python3 -c "import math; d=float('${DURS[$i]}'); print(max(2, math.ceil(d)))" 2>/dev/null || echo "$UNIFORM_DUR")
    else
        D=$UNIFORM_DUR
    fi

    FADE_OUT_START=$((D - FADE))
    if [ "$FADE_OUT_START" -lt 0 ]; then FADE_OUT_START=0; fi

    INPUTS="$INPUTS -loop 1 -t $D -i $img"
    FILTER="${FILTER}[$i:v]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,setsar=1,fade=t=in:st=0:d=${FADE},fade=t=out:st=${FADE_OUT_START}:d=${FADE}[v${i}];"
    echo "  img $((i+1)): ${D}s"
    i=$((i + 1))
done

# Concat filter
CONCAT=""
for j in $(seq 0 $((i - 1))); do
    CONCAT="${CONCAT}[v${j}]"
done
FILTER="${FILTER}${CONCAT}concat=n=${i}:v=1:a=0,format=yuv420p[outv]"

ffmpeg -y $INPUTS -i "$AUDIO" \
    -filter_complex "$FILTER" \
    -map "[outv]" -map "${i}:a" \
    -c:v libx264 -preset fast -crf 23 \
    -c:a aac -b:a 128k \
    -shortest -movflags +faststart \
    "$OUTPUT" 2>&1 | tail -5

if [ -f "$OUTPUT" ] && [ $(stat -f%z "$OUTPUT") -gt 1000 ]; then
    echo "OK: $OUTPUT ($(du -h "$OUTPUT" | cut -f1))"
else
    echo "FAILED: $OUTPUT"
    exit 1
fi
